### ISSUE TITLE
How apply patch to core

### ISSUE THREAD

**Issue by enzolutions** [jpstacey/composer-patcher#4]
Hi JP

I'm wondering if is possible using composer-patcher apply patches to core, I want use in conjunction with https://github.com/tstoeckler/drupal-site-template and apply a lot of non official patches for migrate to create a Distro to enable to migrate from Drupal 7 in a easy way the core elements.

I have around 65 patches to apply, let me know if you think is possible.

**Comment by enzolutions** [comment]
I did a pull request to fix the path https://github.com/tstoeckler/drupal-site-template/pull/7 for sed command

but now I got the following error

```
Generating autoload files
sed: 1: "/Users/enzo/www/drupal- ...": invalid command code e
sed: 1: "/Users/enzo/www/drupal- ...": invalid command code e
sed: 1: "/Users/enzo/www/drupal- ...": invalid command code e
Script scripts/composer/post-install.sh handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output: sed: 1: "/Users/enzo/www/drupal- ...": invalid command code e
  sed: 1: "/Users/enzo/www/drupal- ...": invalid command code e
  sed: 1: "/Users/enzo/www/drupal- ...": invalid command code e
```

**Comment by jpstacey** [comment]
I'm trying to investigate your question, but I don't use composer very often now: I just don't work on those projects!

Since I last used this plugin, composer has removed $event->getPackage() in its most recent API change, so my code no longer works with the most recent composer.phar: https://getcomposer.org/apidoc/master/Composer/Script/Event.html

Also, right now drupal.org is giving me 502 Bad Gateway, so downloading tar files - which you need to do, in order to patch reliably, I think - is not working well enough for me to test.

I think given that the Composer API is changing, and nobody is asking me to work on composer projects right now, I will probably need to retire this package in favour of https://github.com/netresearch/composer-patches-plugin .

But to answer your question, maybe try the netresearch/composer-patches-plugin along with the example composer.json file here:

https://github.com/drupal-composer/drupal-project/blob/7.x/composer.json

Try to add another item to the repositories array, something like:
        {
            "type": "composer",
            "url": "http://packagist.drupal-composer.org"
        },
        {
            "type": "package",
            "package": {
                "name": "drupal/drupal",
                "version": "7.34.0",
                "type": "drupal-core",
                "dist": {
                    "url": "http://ftp.drupal.org/files/projects/drupal-7.34.tgz",
                    "type": "tar"
                }
            }
        }
  
I'm not sure about the "url" field, because d.o is giving me HTTP 502. I hope that helps a bit!

**Comment by jpstacey** [comment]
A relevant discussion has been started here: https://github.com/drupal-composer/drupal-project/issues/14

Others are trying to standardize on a particular package; meanwhile, I've changed the event-handling method to exit with a warning, as I don't believe it works with the current composer Event API.
